apiVersion: v1
kind: Service

metadata:
  name: go-visual-dep
spec:
  selector:
    app: go-visual-dep
  type: LoadBalancer
  ports: 
  - port: 8080
    targetPort: 8000

---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-visual-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-visual-dep
  template:
    metadata:
      labels:
        app: go-visual-dep
    spec:
      containers:
      - name: go-visual-container
        image: nickandr/go-visual


           
